name: Pedro Carmo
description: 'Designer, photographer and artist.'
author: Pedro Carmo - @drocarmo

markdown: kramdown

highlighter: rouge

include:
- .htaccess

exclude:
- README.md
- Rakefile

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

keep_files:
- .git

permalink: /:title
auto: true
