name: Pedro Carmo
description: 'Product Designer'
author: Pedro Carmo - @drocarmo

markdown: kramdown

pygments: true

highlighter: rouge

include:
- .htaccess

exlude:
- assets
- README.md
- Rakefile

keep_files:
- .git

permalink: /:title
